//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersionOne.ServiceHost.ConfigurationTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VersionOne.ServiceHost.ConfigurationTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check priority mappings..
        /// </summary>
        internal static string CheckPriorityMappingsMessage {
            get {
                return ResourceManager.GetString("CheckPriorityMappingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;section name=&quot;Installer&quot; type=&quot;VersionOne.ServiceHost.InstallerConfigurationHandler,VersionOne.ServiceHost&quot; /&gt;
        ///		&lt;section name=&quot;Services&quot; type=&quot;VersionOne.ServiceHost.ServicesConfigurationHandler,VersionOne.ServiceHost.Core&quot; /&gt;
        ///	&lt;/configSections&gt;
        ///	&lt;Installer&gt;
        ///		&lt;ShortName&gt;V1ServiceHost&lt;/ShortName&gt;
        ///		&lt;LongName&gt;VersionOne Service Host&lt;/LongName&gt;
        ///	&lt;/Installer&gt;
        ///	&lt;Services&gt;
        ///    &lt;!-- 
        ///      Listen for LogMessage events and lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationXmlStub {
            get {
                return ResourceManager.GetString("ConfigurationXmlStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        internal static string ConnectionInvalidMessage {
            get {
                return ResourceManager.GetString("ConnectionInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings are valid.
        /// </summary>
        internal static string ConnectionValidMessage {
            get {
                return ResourceManager.GetString("ConnectionValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteIcon {
            get {
                object obj = ResourceManager.GetObject("DeleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorMarkImage {
            get {
                object obj = ResourceManager.GetObject("ErrorMarkImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpBalloonImage {
            get {
                object obj = ResourceManager.GetObject("HelpBalloonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpMarkImage {
            get {
                object obj = ResourceManager.GetObject("HelpMarkImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewFileImage {
            get {
                object obj = ResourceManager.GetObject("NewFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFileImage {
            get {
                object obj = ResourceManager.GetObject("OpenFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveFileImage {
            get {
                object obj = ResourceManager.GetObject("SaveFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File data is invalid, service dependencies are missing. For example, this could happen in the case when Perforce service is configured, and Changeset Writer is not..
        /// </summary>
        internal static string ServiceDependenciesInFileInvalid {
            get {
                return ResourceManager.GetString("ServiceDependenciesInFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected page could not be opened because it requires valid V1 connection. Please make sure you filled in V1 connection details on General page and verified them successfully..
        /// </summary>
        internal static string V1ConnectionRequiredForPage {
            get {
                return ResourceManager.GetString("V1ConnectionRequiredForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon V1Logo {
            get {
                object obj = ResourceManager.GetObject("V1Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Uri is not correct.
        /// </summary>
        internal static string V1ProxyUrlSettingsIsNotCorrect {
            get {
                return ResourceManager.GetString("V1ProxyUrlSettingsIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, server is not accessible or unable to authenticate.
        /// </summary>
        internal static string V1SettingsInvalidMessage {
            get {
                return ResourceManager.GetString("V1SettingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionOne settings are valid.
        /// </summary>
        internal static string V1SettingsValidMessage {
            get {
                return ResourceManager.GetString("V1SettingsValidMessage", resourceCulture);
            }
        }
    }
}
